# Generated by Django 5.2.2 on 2025-06-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_option',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_distance',
            field=models.PositiveIntegerField(blank=True, help_text='Miles from showroom to delivery address', null=True),
        ),
    ]
