# Generated by Django 5.2.2 on 2026-04-13 17:55

import django.core.validators
from django.db import migrations, models


def set_negative_prices_to_zero(apps, schema_editor):
    Car = apps.get_model("showroom", "Car")
    Car.objects.filter(price__lt=0).update(price=0)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_alter_car_image'),
    ]

    operations = [
        migrations.RunPython(set_negative_prices_to_zero, noop_reverse),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
