# Generated by Django 5.2.2 on 2025-07-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_alter_car_price_alter_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_sold',
            field=models.BooleanField(default=False, help_text='Mark True once this car has been sold'),
        ),
    ]
