# Generated by Django 5.2.2 on 2025-07-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='newsletter',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_newsletter_email'),
        ),
    ]
