# Generated by Django 5.2.2 on 2026-04-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_seed_faq_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='HTML or plain text body of the newsletter')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When to send (optional)', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when email was sent', null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0, help_text='Number of subscribers who received it')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
